# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 16:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 25, 16, 41, 28, 305781, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actor',
            name='update',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 25, 16, 42, 11, 944801, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='director',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 25, 16, 42, 16, 439812, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='director',
            name='update',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 25, 16, 42, 19, 290377, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gener',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 25, 16, 42, 21, 799510, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gener',
            name='update',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 25, 16, 42, 23, 644081, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 25, 16, 42, 25, 271430, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='update',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 25, 16, 42, 26, 824492, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='writer',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 25, 16, 42, 28, 319681, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='writer',
            name='update',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 25, 16, 42, 29, 774266, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
