# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='roles',
            field=models.ManyToManyField(through='movies.WorkedOn', to='movies.Role'),
        ),
    ]
