# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_person_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gener',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='gener')),
                ('desccription', models.CharField(blank=True, max_length=200, null=True, verbose_name='gener description')),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='roles',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, to='movies.Gener'),
        ),
    ]
