# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20160322_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='gener',
            field=models.ManyToManyField(to='movies.Gener'),
        ),
    ]
